In [2]:
import json
from pyproj import Proj, transform
import googlemaps
import folium
import pandas as pd

In [3]:
load_df = pd.read_csv("all_coords.csv", encoding = 'EUC-KR')
feature_df = pd.read_csv("total.csv", encoding = 'EUC-KR')

In [11]:
light_df = feature_df[feature_df.분류 == '보안등']
light_df = light_df.drop(columns = ['Unnamed: 0'])
light_df.head(5)

      Unnamed: 0    분류                          명칭         위도          경도
0              0   보안등                     역삼1동833  37.493349  127.032033
1              1   보안등                     역삼1동833  37.493349  127.032033
2              2   보안등                     역삼1동833  37.493349  127.032033
3              3   보안등                     역삼1동833  37.493349  127.032033
4              4   보안등                     역삼1동833  37.493349  127.032033
5              5   보안등                  역삼1동832-25  37.492834  127.031413
6              6   보안등                  역삼1동832-27  37.492632  127.031508
7              7   보안등                  역삼1동832-28  37.492480  127.031581
8              8   보안등                  역삼1동832-28  37.492480  127.031581
9              9   보안등                  역삼1동832-29  37.492343  127.031644
10            10   보안등                  역삼1동832-31  37.492030  127.031693
11            11   보안등                  역삼1동832-31  37.492030  127.031693
12            12   보안등                  역삼1동837-33  37.491576  127.032010
13            13   보안등                  역삼1동837-15  37.491900  127.032159
14            14   보안등                  역삼1동837-16  37.491957  127.032354
15            15   보안등                     역삼1동836  37.491975  127.033001
16            16   보안등                   역삼1동836-1  37.491622  127.032847
17            17   보안등                   역삼1동836-2  37.491662  127.032987
18            18   보안등                  역삼1동836-14  37.491485  127.033077
19            19   보안등                  역삼1동836-15  37.491442  127.032932
20            20   보안등                  역삼1동836-25  37.490908  127.033181
21            21   보안등                   역삼1동840-1  37.491164  127.035348
22            22   보안등                   역삼1동840-3  37.491250  127.035637
23            23   보안등                   역삼1동840-5  37.491322  127.035881
24            24   보안등                   역삼1동840-5  37.491322  127.035881
25            25   보안등                  역삼1동835-51  37.491654  127.036130
26            26   보안등                     역삼1동799  37.491589  127.036736
27            27   보안등                  역삼1동835-52  37.491715  127.036320
28            28   보안등                  역삼1동793-52  37.491942  127.036542
29            29   보안등                  역삼1동835-68  37.492310  127.035778
...          ...   ...                         ...        ...         ...
2060        2060  CCTV                  역삼동 721-28  37.499869  127.042979
2061        2061  CCTV                  역삼동 725-25  37.500484  127.040338
2062        2062  CCTV         역삼동 702-1(역삼지하보도 내)  37.502510  127.042772
2063        2063  CCTV                  역삼동 783-16  37.494971  127.044339
2064        2064  CCTV                  역삼동 792-38  37.493998  127.036990
2065        2065  CCTV         역삼동 795-26 (역삼마을마당)  37.492384  127.038624
2066        2066  CCTV  역삼동 707-42 (한신인터밸리24빌딩 주변)  37.503007  127.047533
2067        2067  CCTV                   역삼동 832-7  37.491684  127.030863
2068        2068  CCTV       역삼동 755 (이마트 역삼지점 주변)  37.499448  127.047839
2069        2069  CCTV        역삼동 649-10 (서림빌딩 주변)  37.499148  127.029728
2070        2070  CCTV                   역삼동 719-9  37.501015  127.040258
2071        2071  CCTV                  역삼동 619-23  37.501641  127.027291
2072        2072  CCTV                   역삼동 661-8  37.506303  127.038241
2073        2073  CCTV                  역삼동 683-19  37.508272  127.044262
2074        2074  CCTV                  역삼동 809-12  37.502840  127.026111
2075        2075  CCTV                  역삼동 766-18  37.495777  127.050062
2076        2076  CCTV                  역삼동 644-17  37.500915  127.034548
2077        2077  CCTV                   역삼동 635-1  37.500066  127.030474
2078        2078  CCTV                  역삼동 613-22  37.505412  127.030715
2079        2079  CCTV                  역삼동 776-25  37.494584  127.040761
2080        2080  CCTV                  역삼동 775-29  37.495559  127.041465
2081        2081  CCTV                   역삼동 635-1  37.501634  127.029524
2082        2082  CCTV                     역삼동 647  37.500549  127.032305
2083        2083  CCTV                  역삼동 756-19  37.497678  127.051659
2084        2084  CCTV                  역삼동 791-23  37.494107  127.039046
2085        2085  CCTV                  역삼동 645-29  37.500952  127.034029
2086        2086  CCTV                   역삼동 697-7  37.505768  127.046191
2087        2087  CCTV                  역삼동 700-13  37.504978  127.042522
2088        2088  CCTV                   역삼동 652-5  37.508216  127.037184
2089        2089  CCTV                  역삼동 735-18  37.497878  127.033595

[2090 rows x 5 columns]

In [5]:
load_df = load_df.loc[:, ['RN', 'LAT', 'LNG']]
load_df['분류'] = '도로'
load_df.head(1)

    RN       LAT         LNG  분류
0  역삼로  37.49303  127.029968  도로

In [6]:
load_df.rename(index=str, columns={ "RN" : "명칭","LAT"  : "위도", "LNG" : "경도" },inplace=True)
load_df.head(4)

    명칭         위도          경도  분류
0  역삼로  37.493030  127.029968  도로
1  역삼로  37.493107  127.030238  도로
2  역삼로  37.493325  127.030953  도로
3  역삼로  37.493571  127.031758  도로

In [7]:
total_load = pd.concat([load_df,light_df]).reset_index(drop=True)
total_load.head(4)

C:\Users\arara\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

           경도   명칭  분류         위도
0  127.029968  역삼로  도로  37.493030
1  127.030238  역삼로  도로  37.493107
2  127.030953  역삼로  도로  37.493325
3  127.031758  역삼로  도로  37.493571

In [8]:
total_load.loc[:,['명칭','분류', '위도','경도' ]].to_csv("total_load_points.csv", mode='w', encoding='ms949') # edge(=link) list